baseurl = "https://sitescomputer.github.io/SCR-Mailer/"
languageCode = "en-us"
title = "SCR Mailer | Sites Computer Resources"

[params]
  productName = "SCR Mailer"
  companyName = "Sites Computer Resources"
  companyURL = "https://github.com/sitescomputer/SCR-Mailer"
  repositoryURL = "https://github.com/sitescomputer/SCR-Mailer"

[taxonomies]
  tag = "tags"
