version: 2
project_name: scr-mailer

env:
  - GO111MODULE=on
  - CGO_ENABLED=0

before:
  hooks:
    - make build-frontend

builds:
  - id: scr-mailer
    binary: scr-mailer
    main: ./cmd
    goos: [linux, windows, darwin, freebsd, openbsd, netbsd]
    goarch: [amd64, arm64, arm]
    goarm: ["6", "7"]
    ignore:
      - goos: windows
        goarch: arm
    ldflags:
      - -s -w -X "main.buildString={{ .Tag }} ({{ .ShortCommit }} {{ .Date }}, {{ .Os }}/{{ .Arch }})" -X "main.versionString={{ .Tag }}"
    hooks:
      post: make pack-bin BIN={{ .Path }}

archives:
  - formats: [tar.gz]
    format_overrides:
      - goos: windows
        formats: [zip]
    files:
      - README.md
      - LICENSE
      - UPSTREAM.md
      - branding/README.md

checksum:
  name_template: checksums.txt

release:
  github:
    owner: sitescomputer
    name: SCR-Mailer
  name_template: "SCR Mailer {{ .Tag }}"
